name: torch_env
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.6.1=h63175ca_0
  - asttokens=3.0.0=py310haa95532_0
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.16.0=h0ac17fb_1012
  - certifi=2026.01.04=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.3=py310haa95532_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cuda-cccl=13.1.115=h415d894_0
  - cuda-cccl_win-64=13.1.115=hc667259_0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.115=hd7d98ca_0
  - cuda-opencl-dev=13.1.115=hd7d98ca_0
  - cuda-profiler-api=13.1.115=h415d894_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.16=py310h885b0b7_1
  - decorator=5.2.1=py310haa95532_0
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - fastapi=0.128.7=h877c79a_0
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.128.7=pyhcf101f3_0
  - ffmpeg=5.1.2=gpl_h8bb4bc8_112
  - filelock=3.20.3=py310haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=hfbffc0b_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h7edc060_0
  - glib=2.84.0=h3d4babf_0
  - glib-tools=2.84.0=h4394cf3_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py310h8598115_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=6.0.0=he256f1b_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py310h29418f3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h0e60522_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.31.0=py310h4442805_0
  - ipython=8.30.0=py310haa95532_0
  - jasper=2.0.33=hc2e4405_1
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.8.0=py310haa95532_0
  - jupyter_core=5.9.1=py310haa95532_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.1.81=hd7d98ca_0
  - libcurand-dev=10.4.1.81=hd7d98ca_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=13_h018ca30_netlib
  - liblapacke=3.9.0=13_h0d55cca_netlib
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.7.0=py310h90026ac_1
  - libopus=1.6.1=h6a83c73_0
  - libpng=1.6.54=ha15c746_0
  - libprotobuf=3.21.12=h12be248_2
  - libsodium=1.0.20=h83e8143_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib=3.9.1=py310h5588dad_1
  - matplotlib-base=3.9.1=py310h37e0a56_2
  - matplotlib-inline=0.2.1=py310haa95532_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - opencv=4.7.0=py310h5588dad_1
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py310haa95532_1
  - parso=0.8.5=py310haa95532_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.1.0=py310h096bfcc_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=py310haa95532_0
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=py310haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310h02ab6af_1
  - pure_eval=0.2.3=py310haa95532_0
  - py-opencv=4.7.0=py310hbbfc1a7_1
  - pycparser=2.23=py310haa95532_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310h034784e_1
  - pydantic-extra-types=2.11.0=pyhcf101f3_1
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=py310haa95532_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.9=py310h1fd54f2_5
  - pyqt5-sip=12.12.2=py310h00ffb61_5
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.22=pyhcf101f3_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py310h885b0b7_0
  - pyyaml=6.0.3=py310hb9a58be_0
  - pyzmq=27.1.0=py310h7149c55_1
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.8=h720456b_6
  - requests=2.32.5=py310haa95532_1
  - rich=14.3.2=pyhcf101f3_0
  - rich-toolkit=0.19.2=pyhcf101f3_0
  - setuptools=80.10.2=py310haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sip=6.7.12=py310h00ffb61_0
  - six=1.17.0=py310haa95532_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py310haa95532_0
  - starlette=0.52.1=pyhfdc7a7d_0
  - svt-av1=1.4.1=h63175ca_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py310h02ab6af_0
  - tqdm=4.67.1=py310h4442805_1
  - traitlets=5.14.3=py310haa95532_0
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - urllib3=2.6.3=py310haa95532_0
  - uvicorn=0.40.0=pyh6dadd2b_0
  - uvicorn-standard=0.40.0=hcfb189c_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchfiles=1.1.1=py310hf13f778_0
  - wcwidth=0.2.14=py310haa95532_0
  - websockets=16.0=py310h1637853_1
  - wheel=0.46.3=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - fsspec==2024.6.1
      - moderncnn-project==1.0.0
      - rescigit-net==1.0.0
      - sympy==1.13.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
prefix: C:\Users\ayson\.conda\envs\torch_env
